use std::collections::HashMap;

pub fn get_licensee_codes() -> HashMap<u8, &'static str> {
    let mut licencee_codes: HashMap<u8, &str> = HashMap::new();
    licencee_codes.insert(0, "None");
    licencee_codes.insert(1, "Nintendo R&D1");
    licencee_codes.insert(8, "Capcom");
    licencee_codes.insert(13, "Electronic Arts");
    licencee_codes.insert(18, "Hudson Soft");
    licencee_codes.insert(19, "b-ai");
    licencee_codes.insert(20, "kss");
    licencee_codes.insert(22, "pow");
    licencee_codes.insert(24, "PCM Complete");
    licencee_codes.insert(25, "san-x");
    licencee_codes.insert(28, "Kemco Japan");
    licencee_codes.insert(29, "seta");
    licencee_codes.insert(30, "Viacom");
    licencee_codes.insert(31, "Nintendo");
    licencee_codes.insert(32, "Bandai");
    licencee_codes.insert(33, "Ocean/Acclaim");
    licencee_codes.insert(34, "Konami");
    licencee_codes.insert(35, "Hector");
    licencee_codes.insert(37, "Taito");
    licencee_codes.insert(38, "Hudson");
    licencee_codes.insert(39, "Banpresto");
    licencee_codes.insert(41, "Ubi Soft");
    licencee_codes.insert(42, "Atlus");
    licencee_codes.insert(44, "Malibu");
    licencee_codes.insert(46, "angel");
    licencee_codes.insert(47, "Bullet-Proof");
    licencee_codes.insert(49, "irem");
    licencee_codes.insert(50, "Absolute");
    licencee_codes.insert(51, "Acclaim");
    licencee_codes.insert(52, "Activision");
    licencee_codes.insert(53, "American sammy");
    licencee_codes.insert(54, "Konami");
    licencee_codes.insert(55, "Hi tech entertainment");
    licencee_codes.insert(56, "LJN");
    licencee_codes.insert(57, "Matchbox");
    licencee_codes.insert(58, "Mattel");
    licencee_codes.insert(59, "Milton Bradley");
    licencee_codes.insert(60, "Titus");
    licencee_codes.insert(61, "Virgin");
    licencee_codes.insert(64, "LucasArts");
    licencee_codes.insert(67, "Ocean");
    licencee_codes.insert(69, "Electronic Arts");
    licencee_codes.insert(70, "Infogrames");
    licencee_codes.insert(71, "Interplay");
    licencee_codes.insert(72, "Broderbund");
    licencee_codes.insert(73, "sculptured");
    licencee_codes.insert(75, "sci");
    licencee_codes.insert(78, "THQ");
    licencee_codes.insert(79, "Accolade");
    licencee_codes.insert(80, "misawa");
    licencee_codes.insert(83, "lozc");
    licencee_codes.insert(86, "Tokuma Shoten Intermedia");
    licencee_codes.insert(87, "Tsukuda Original");
    licencee_codes.insert(91, "Chunsoft");
    licencee_codes.insert(92, "Video system");
    licencee_codes.insert(93, "Ocean/Acclaim");
    licencee_codes.insert(95, "Varie");
    licencee_codes.insert(96, "Yonezawa/s’pal");
    licencee_codes.insert(97, "Kaneko");
    licencee_codes.insert(99, "Pack in soft");
    licencee_codes.insert(0xA4, "Konami (Yu-Gi-Oh!)");
    return licencee_codes;
}

pub fn get_old_licencee_codes() -> HashMap<u8, &'static str> {
    let mut old_licencee_codes: HashMap<u8, &str> = HashMap::new();
    old_licencee_codes.insert(0x00, "none");
    old_licencee_codes.insert(0x01, "Nintendo");
    old_licencee_codes.insert(0x08, "capcom");
    old_licencee_codes.insert(0x09, "hot-b");
    old_licencee_codes.insert(0x0A, "jaleco");
    old_licencee_codes.insert(0x0B, "coconuts");
    old_licencee_codes.insert(0x0C, "elite systems");
    old_licencee_codes.insert(0x13, "electronic arts");
    old_licencee_codes.insert(0x18, "hudsonsoft");
    old_licencee_codes.insert(0x19, "itc entertainment");
    old_licencee_codes.insert(0x1A, "yanoman");
    old_licencee_codes.insert(0x1D, "clary");
    old_licencee_codes.insert(0x1F, "virgin");
    old_licencee_codes.insert(0x24, "pcm complete");
    old_licencee_codes.insert(0x25, "san-x");
    old_licencee_codes.insert(0x28, "kotobuki systems");
    old_licencee_codes.insert(0x29, "seta");
    old_licencee_codes.insert(0x30, "infogrames");
    old_licencee_codes.insert(0x31, "nintendo");
    old_licencee_codes.insert(0x32, "bandai");
    old_licencee_codes.insert(0x33, "\"see above\"");
    old_licencee_codes.insert(0x34, "konami");
    old_licencee_codes.insert(0x35, "hector");
    old_licencee_codes.insert(0x38, "capcom");
    old_licencee_codes.insert(0x39, "banpresto");
    old_licencee_codes.insert(0x3C, "*entertainment i");
    old_licencee_codes.insert(0x3E, "gremlin");
    old_licencee_codes.insert(0x41, "ubi soft");
    old_licencee_codes.insert(0x42, "atlus");
    old_licencee_codes.insert(0x44, "malibu");
    old_licencee_codes.insert(0x46, "angel");
    old_licencee_codes.insert(0x47, "spectrum holoby");
    old_licencee_codes.insert(0x49, "irem");
    old_licencee_codes.insert(0x4A, "virgin");
    old_licencee_codes.insert(0x4D, "malibu");
    old_licencee_codes.insert(0x4F, "u.s. gold");
    old_licencee_codes.insert(0x50, "absolute");
    old_licencee_codes.insert(0x51, "acclaim");
    old_licencee_codes.insert(0x52, "activision");
    old_licencee_codes.insert(0x53, "american sammy");
    old_licencee_codes.insert(0x54, "gametek");
    old_licencee_codes.insert(0x55, "park place");
    old_licencee_codes.insert(0x56, "ljn");
    old_licencee_codes.insert(0x57, "matchbox");
    old_licencee_codes.insert(0x59, "milton bradley");
    old_licencee_codes.insert(0x5A, "mindscape");
    old_licencee_codes.insert(0x5B, "romstar");
    old_licencee_codes.insert(0x5C, "naxat soft");
    old_licencee_codes.insert(0x5D, "tradewest");
    old_licencee_codes.insert(0x60, "titus");
    old_licencee_codes.insert(0x61, "virgin");
    old_licencee_codes.insert(0x67, "ocean");
    old_licencee_codes.insert(0x69, "electronic arts");
    old_licencee_codes.insert(0x6E, "elite systems");
    old_licencee_codes.insert(0x6F, "electro brain");
    old_licencee_codes.insert(0x70, "infogrames");
    old_licencee_codes.insert(0x71, "interplay");
    old_licencee_codes.insert(0x72, "broderbund");
    old_licencee_codes.insert(0x73, "sculptered soft");
    old_licencee_codes.insert(0x75, "the sales curve");
    old_licencee_codes.insert(0x78, "t*hq");
    old_licencee_codes.insert(0x79, "accolade");
    old_licencee_codes.insert(0x7A, "triffix entertainment");
    old_licencee_codes.insert(0x7C, "microprose");
    old_licencee_codes.insert(0x7F, "kemco");
    old_licencee_codes.insert(0x80, "misawa entertainment");
    old_licencee_codes.insert(0x83, "lozc");
    old_licencee_codes.insert(0x86, "*tokuma shoten i");
    old_licencee_codes.insert(0x8B, "bullet-proof software");
    old_licencee_codes.insert(0x8C, "vic tokai");
    old_licencee_codes.insert(0x8E, "ape");
    old_licencee_codes.insert(0x8F, "i'max");
    old_licencee_codes.insert(0x91, "chun soft");
    old_licencee_codes.insert(0x92, "video system");
    old_licencee_codes.insert(0x93, "tsuburava");
    old_licencee_codes.insert(0x95, "varie");
    old_licencee_codes.insert(0x96, "yonezawa/s'pal");
    old_licencee_codes.insert(0x97, "kaneko");
    old_licencee_codes.insert(0x99, "arc");
    old_licencee_codes.insert(0x9A, "nihon bussan");
    old_licencee_codes.insert(0x9B, "tecmo");
    old_licencee_codes.insert(0x9C, "imagineer");
    old_licencee_codes.insert(0x9D, "banpresto");
    old_licencee_codes.insert(0x9F, "nova");
    old_licencee_codes.insert(0xA1, "hori electric");
    old_licencee_codes.insert(0xA2, "bandai");
    old_licencee_codes.insert(0xA4, "konami");
    old_licencee_codes.insert(0xA6, "kawada");
    old_licencee_codes.insert(0xA7, "takara");
    old_licencee_codes.insert(0xA9, "technos japan");
    old_licencee_codes.insert(0xAA, "broderbund");
    old_licencee_codes.insert(0xAC, "toei animation");
    old_licencee_codes.insert(0xAD, "toho");
    old_licencee_codes.insert(0xAF, "namco");
    old_licencee_codes.insert(0xB0, "acclaim");
    old_licencee_codes.insert(0xB1, "ascii or nexoft");
    old_licencee_codes.insert(0xB2, "bandai");
    old_licencee_codes.insert(0xB4, "enix");
    old_licencee_codes.insert(0xB6, "hal");
    old_licencee_codes.insert(0xB7, "snk");
    old_licencee_codes.insert(0xB9, "pony canyon");
    old_licencee_codes.insert(0xBA, "*culture brain o");
    old_licencee_codes.insert(0xBB, "sunsoft");
    old_licencee_codes.insert(0xBD, "sony imagesoft");
    old_licencee_codes.insert(0xBF, "sammy");
    old_licencee_codes.insert(0xC0, "taito");
    old_licencee_codes.insert(0xC2, "kemco");
    old_licencee_codes.insert(0xC3, "squaresoft");
    old_licencee_codes.insert(0xC4, "*tokuma shoten i");
    old_licencee_codes.insert(0xC5, "data east");
    old_licencee_codes.insert(0xC6, "tonkin house");
    old_licencee_codes.insert(0xC8, "koei");
    old_licencee_codes.insert(0xC9, "ufl");
    old_licencee_codes.insert(0xCA, "ultra");
    old_licencee_codes.insert(0xCB, "vap");
    old_licencee_codes.insert(0xCC, "use");
    old_licencee_codes.insert(0xCD, "meldac");
    old_licencee_codes.insert(0xCE, "*pony canyon or");
    old_licencee_codes.insert(0xCF, "angel");
    old_licencee_codes.insert(0xD0, "taito");
    old_licencee_codes.insert(0xD1, "sofel");
    old_licencee_codes.insert(0xD2, "quest");
    old_licencee_codes.insert(0xD3, "sigma enterprises");
    old_licencee_codes.insert(0xD4, "ask kodansha");
    old_licencee_codes.insert(0xD6, "naxat soft");
    old_licencee_codes.insert(0xD7, "copya systems");
    old_licencee_codes.insert(0xD9, "banpresto");
    old_licencee_codes.insert(0xDA, "tomy");
    old_licencee_codes.insert(0xDB, "ljn");
    old_licencee_codes.insert(0xDD, "ncs");
    old_licencee_codes.insert(0xDE, "human");
    old_licencee_codes.insert(0xDF, "altron");
    old_licencee_codes.insert(0xE0, "jaleco");
    old_licencee_codes.insert(0xE1, "towachiki");
    old_licencee_codes.insert(0xE2, "uutaka");
    old_licencee_codes.insert(0xE3, "varie");
    old_licencee_codes.insert(0xE5, "epoch");
    old_licencee_codes.insert(0xE7, "athena");
    old_licencee_codes.insert(0xE8, "asmik");
    old_licencee_codes.insert(0xE9, "natsume");
    old_licencee_codes.insert(0xEA, "king records");
    old_licencee_codes.insert(0xEB, "atlus");
    old_licencee_codes.insert(0xEC, "epic/sony records");
    old_licencee_codes.insert(0xEE, "igs");
    old_licencee_codes.insert(0xF0, "a wave");
    old_licencee_codes.insert(0xF3, "extreme entertainment");
    old_licencee_codes.insert(0xFF, "ljn");
    return old_licencee_codes;
}
